#!/usr/bin/env python3
"""Generate the bundled common-foods table for both apps.

`data/common_foods.json` is the single source of truth. This script emits:

  web/foods.js            — assigns window.FOODIE_COMMON_FOODS
  ios/Foodie/CommonFoods.swift — a compiled-in Swift array

Both are committed so neither app needs a build step or a network call.

    python3 scripts/gen_foods.py
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "common_foods.json"
WEB_OUT = ROOT / "web" / "foods.js"
IOS_OUT = ROOT / "ios" / "Foodie" / "CommonFoods.swift"

BANNER = "// Generated by scripts/gen_foods.py from data/common_foods.json — do not edit by hand."


def load():
    data = json.loads(SRC.read_text(encoding="utf-8"))
    foods = data["foods"]

    seen = set()
    for f in foods:
        for key in ("id", "name", "kcal", "p", "c", "f"):
            if key not in f:
                sys.exit(f"error: food {f.get('id', '?')} is missing '{key}'")
        if f["id"] in seen:
            sys.exit(f"error: duplicate food id '{f['id']}'")
        seen.add(f["id"])
        for label, grams in f.get("servings", []):
            if not isinstance(grams, (int, float)) or grams <= 0:
                sys.exit(f"error: food {f['id']} has a bad serving '{label}'")

    foods.sort(key=lambda f: f["name"].lower())
    return foods


def gen_web(foods):
    """Compact array-of-arrays keeps the payload small; foods.js unpacks it."""
    rows = [
        [f["id"], f["name"], f["kcal"], f["p"], f["c"], f["f"],
         [[label, grams] for label, grams in f.get("servings", [])]]
        for f in foods
    ]
    body = ",\n  ".join(json.dumps(r, separators=(",", ":")) for r in rows)
    return (
        f"/* {BANNER[3:]} */\n"
        "/* Rows: [id, name, kcal, protein, carbs, fat, [[servingLabel, grams], ...]]\n"
        "   Macros are per 100 g edible portion. */\n"
        "window.FOODIE_COMMON_FOODS = [\n  "
        f"{body}\n];\n"
    )


def swift_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def gen_ios(foods):
    lines = [
        BANNER,
        "",
        "import Foundation",
        "",
        "/// The offline table of common whole foods, shared with the web app.",
        "/// Macros are per 100 g edible portion.",
        "enum CommonFoods {",
        "    static let all: [CommonFood] = [",
    ]
    for f in foods:
        servings = ", ".join(
            f"Serving(label: {swift_str(label)}, grams: {float(grams)})"
            for label, grams in f.get("servings", [])
        )
        lines.append(
            f"        CommonFood(id: {swift_str(f['id'])}, name: {swift_str(f['name'])}, "
            f"kcal: {float(f['kcal'])}, protein: {float(f['p'])}, "
            f"carbs: {float(f['c'])}, fat: {float(f['f'])}, "
            f"servings: [{servings}]),"
        )
    lines += ["    ]", "}", ""]
    return "\n".join(lines)


def main():
    foods = load()
    WEB_OUT.write_text(gen_web(foods), encoding="utf-8")
    IOS_OUT.write_text(gen_ios(foods), encoding="utf-8")
    print(f"wrote {len(foods)} foods -> {WEB_OUT.relative_to(ROOT)}, {IOS_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
